### ISSUE TITLE
Check if plugin is used for doesntexists case

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-manage-theme-plugins#4]
In case the plugin is not used (should be deactivated), we should not prompt doesntexists errors. Because some plugins are required only on dev with composer for exemple.

We must add a check to see if plugin must / should be deactivted.
@see https://github.com/BeAPI/bea-manage-theme-plugins/blob/master/classes/admin/main.php#L86

**Comment by herewithme** [comment]
Not applicable following the refactoring.
