### ISSUE TITLE
WP CLI command name

### ISSUE THREAD

**Issue by ghost** [BeAPI/bea-manage-theme-plugins#7]
Are you sure about the name ?

`\WP_CLI::add_command( 'plugins'`

"plugins" seems very generic, I mean if someone misses the final "s" then it's another command, a built-in command https://developer.wordpress.org/cli/commands/plugin/, it might be confusing.

Not sayin' the name should be changed, just want your opinion about that ^^.

**Comment by herewithme** [comment]
@TweetPressFr You're absolutely right, it's changed in this commit: https://github.com/BeAPI/bea-manage-theme-plugins/commit/7b26af9556d77da875eddf73a08d790b1a931e2b
